In [1]:
import pandas as pd

raw_data = pd.read_json("items.json")
raw_data.describe()

,answer_count,articles_count,favorited_count,follower_count,following_count,gender,thanked_count,voteup_count
count,100018.000000,100018.000000,1.000180e+05,1.000180e+05,100018.000000,100018.000000,100018.000000,1.000180e+05
mean,37.449999,4.451159,1.283739e+03,7.855568e+02,112.203903,-0.045152,370.752565,2.452141e+03
std,141.592722,34.148088,1.474934e+04,1.098500e+04,335.405797,0.831423,3864.296782,2.743925e+04
min,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,-1.000000,0.000000,0.000000e+00
25%,0.000000,0.000000,0.000000e+00,1.000000e+00,7.000000,-1.000000,0.000000,0.000000e+00
50%,4.000000,0.000000,2.000000e+00,1.100000e+01,24.000000,0.000000,1.000000,1.000000e+01
75%,24.000000,0.000000,1.580000e+02,1.340000e+02,87.000000,1.000000,68.000000,4.220000e+02
max,8067.000000,3431.000000,2.467795e+06,2.123468e+06,11205.000000,1.000000,794983.000000,6.308619e+06

In [2]:
for ele in raw_data:
  print(ele)

answer_count
articles_count
avatar_url
business
description
educations
employments
favorited_count
follower_count
following_count
gender
headline
locations
name
thanked_count
url_token
user_type
voteup_count